const en = {
  skipContent:'Skip to content', saved: 'Saved', showPassword: 'Show', hidePassword: 'Hide', moreOptions: 'Additional settings', retry: 'Try again', unread: 'Unread',
  working: 'Working…', reviewForm: 'Review the highlighted fields.', profile: 'Profile', display: 'Display & language',
  posts: 'Posts & timeline', communication: 'Notifications & messages', security: 'Security', integrations: 'Integrations & developer tools',
  danger: 'Account deletion', aboutLead: 'Share what you love. Find your people. Choose who can see your posts.',
  emptyPublic: 'Be part of the first conversation.', back: 'Back', submitHint: 'Complete the required fields and agree to the terms before registering.',
};
export const uxMessages = {
  en,
  ja: { skipContent:'本文へ移動', saved:'保存しました', showPassword:'表示', hidePassword:'隠す', moreOptions:'追加設定', retry:'再試行', unread:'未読', working:'処理中…', reviewForm:'入力内容を確認してください。', profile:'プロフィール', display:'表示・言語', posts:'投稿・タイムライン', communication:'通知・メッセージ', security:'セキュリティ', integrations:'連携・開発者', danger:'アカウント削除', aboutLead:'好きなことを投稿して、気の合う人とつながる。公開する相手も、自分で選べます。', emptyPublic:'最初の会話に参加してみませんか。', back:'戻る', submitHint:'必須項目を入力し、利用規約への同意を確認して登録してください。' },
  zh: { ...en, skipContent:'跳转到正文', saved:'已保存', showPassword:'显示', hidePassword:'隐藏', moreOptions:'更多设置', retry:'重试', unread:'未读', working:'处理中…', reviewForm:'请检查输入内容。', profile:'个人资料', display:'显示与语言', posts:'帖子与时间线', communication:'通知与消息', security:'安全', integrations:'集成与开发者', danger:'删除账户', aboutLead:'分享热爱，找到同好，自由选择谁能看到你的帖子。', emptyPublic:'加入第一场对话。', back:'返回', submitHint:'请填写必填项并同意条款后注册。' },
  ko: { ...en, skipContent:'본문으로 이동', saved:'저장했습니다', showPassword:'표시', hidePassword:'숨기기', moreOptions:'추가 설정', retry:'다시 시도', unread:'읽지 않음', working:'처리 중…', reviewForm:'입력 내용을 확인해 주세요.', profile:'프로필', display:'화면·언어', posts:'게시물·타임라인', communication:'알림·메시지', security:'보안', integrations:'연동·개발자', danger:'계정 삭제', aboutLead:'좋아하는 것을 공유하고 마음이 맞는 사람들과 만나세요. 공개 대상도 직접 선택하세요.', emptyPublic:'첫 대화에 참여해 보세요.', back:'뒤로', submitHint:'필수 항목을 입력하고 이용약관에 동의한 후 가입하세요.' },
  ru: { ...en, skipContent:'Перейти к содержимому', saved:'Сохранено', showPassword:'Показать', hidePassword:'Скрыть', moreOptions:'Дополнительные настройки', retry:'Повторить', unread:'Не прочитано', working:'Обработка…', reviewForm:'Проверьте введённые данные.', profile:'Профиль', display:'Оформление и язык', posts:'Публикации и лента', communication:'Уведомления и сообщения', security:'Безопасность', integrations:'Интеграции и разработка', danger:'Удаление аккаунта', aboutLead:'Делитесь любимым, находите единомышленников и выбирайте, кто видит ваши публикации.', emptyPublic:'Начните первый разговор.', back:'Назад', submitHint:'Заполните обязательные поля и примите условия для регистрации.' },
  es: { ...en, skipContent:'Ir al contenido', saved:'Guardado', showPassword:'Mostrar', hidePassword:'Ocultar', moreOptions:'Más opciones', retry:'Reintentar', unread:'Sin leer', working:'Procesando…', reviewForm:'Revisa los campos indicados.', profile:'Perfil', display:'Apariencia e idioma', posts:'Publicaciones y cronología', communication:'Notificaciones y mensajes', security:'Seguridad', integrations:'Integraciones y desarrollo', danger:'Eliminar cuenta', aboutLead:'Comparte lo que te gusta, encuentra tu comunidad y elige quién ve tus publicaciones.', emptyPublic:'Participa en la primera conversación.', back:'Volver', submitHint:'Completa los campos obligatorios y acepta las condiciones para registrarte.' },
  pt: { ...en, skipContent:'Ir para o conteúdo', saved:'Salvo', showPassword:'Mostrar', hidePassword:'Ocultar', moreOptions:'Mais opções', retry:'Tentar novamente', unread:'Não lida', working:'Processando…', reviewForm:'Revise os campos indicados.', profile:'Perfil', display:'Aparência e idioma', posts:'Publicações e linha do tempo', communication:'Notificações e mensagens', security:'Segurança', integrations:'Integrações e desenvolvimento', danger:'Excluir conta', aboutLead:'Compartilhe o que você gosta, encontre sua comunidade e escolha quem vê suas publicações.', emptyPublic:'Participe da primeira conversa.', back:'Voltar', submitHint:'Preencha os campos obrigatórios e aceite os termos para se cadastrar.' },
};
